"""Artifact-wide constants."""

DEFAULT_DATASETS = ("MB1", "MB2")
DEFAULT_ROUNDS = (1, 2, 3)
DEFAULT_WINDOW_DAYS = 30
DEFAULT_PATCH_LENGTH = 5
DEFAULT_HEALTHY_PER_FAILED = 23.0
DEFAULT_SAMPLE_SEED = 2026
